In [8]:
from sklearn import svm
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = pd.read_csv('glass.csv')
y = data['Type']
x = data.drop('Type', 1)

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25)

linear = svm.SVC(kernel='linear')
linear.fit(xtrain, ytrain)
ypred1 = linear.predict(xtest)

#print(linear.support_vectors_)
#print(linear.n_support_)

print("Accuracy Of Linear Kernel: ", accuracy_score(ytest, ypred1))
print("Confusion Matrix: \n", confusion_matrix(ytest, ypred1))
print("Classification report: \n", classification_report(ytest, ypred1))

sigmoid = svm.SVC(kernel='sigmoid')
sigmoid.fit(xtrain, ytrain)
ypred2 = sigmoid.predict(xtest)
print("\n Accuracy Of Sigmoid Kernel: ", accuracy_score(ytest, ypred2))
print("\n Confusion Matrix: \n", confusion_matrix(ytest, ypred2))
print("\nClassification report: \n", classification_report(ytest, ypred2))

poly = svm.SVC(kernel='poly')
poly.fit(xtrain, ytrain)
ypred3 = poly.predict(xtest)
print("\n Accuracy Of Ploy Kernel: ", accuracy_score(ytest, ypred3))
print("\n Confusion Matrix: \n", confusion_matrix(ytest, ypred3))
print("\n Classification report: \n", classification_report(ytest, ypred3))


rbf = svm.SVC(kernel='rbf')
rbf.fit(xtrain, ytrain)
ypred4 = rbf.predict(xtest)
print("\n Accuracy Of RBF Kernel:\n ", accuracy_score(ytest, ypred4))
print("\n Confusion Matrix: \n", confusion_matrix(ytest, ypred4))
print("\n Classification report: \n", classification_report(ytest, ypred4))


Accuracy Of Linear Kernel:  1.0
Confusion Matrix: 
 [[17  0  0  0  0  0]
 [ 0 18  0  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  8]]
Classification report: 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00         6
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         8

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

Accuracy Of Sigmoid Kernel:  0.5740740740740741
Confusion Matrix: 
 [[13  4  0  0  0  0]
 [ 0 18  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  3  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  8  0  0  0  0]]
Classification report: 
               precision    recall

/tmp/ipykernel_69990/3134683576.py:9: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = data.drop('Type', 1)
/home/aditya/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/aditya/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/aditya/.local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set

fatal: destination path 'svm' already exists and is not an empty directory.
